"""Configuration values for the Bang RL project."""

# Arena dimensions
GRID_WIDTH_TILES = 32
GRID_HEIGHT_TILES = 24
TILE_SIZE = 20
BOTTOM_BAR_HEIGHT = 30
BOTTOM_BAR_MARGIN = 20
SCREEN_WIDTH = GRID_WIDTH_TILES * TILE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT_TILES * TILE_SIZE + BOTTOM_BAR_HEIGHT

# Runtime options
FPS = 60
TRAINING_FPS = 0  # 0 lets pygame run unlocked for faster headless training
SHOW_GAME = False
PLOT_TRAINING = False
USE_GPU = False

# Colors
COLOR_PLAYER = (30, 100, 100)
COLOR_PLAYER_OUTLINE = (50, 215, 200)
COLOR_ENEMY = (125, 45, 45)
COLOR_ENEMY_OUTLINE = (240, 95, 95)
COLOR_OBSTACLE_OUTLINE = (125, 125, 125)
COLOR_OBSTACLE_FILL = (45, 45, 45)
COLOR_PROJECTILE = (235, 195, 50)
COLOR_BACKGROUND = (45, 45, 45)
COLOR_SCORE = (255, 255, 255)


# Legacy color aliases (kept so UI colors match the original project naming)
COLOR_LEFT_TEAM = COLOR_PLAYER
COLOR_LEFT_TEAM_OUTLINE = COLOR_PLAYER_OUTLINE
COLOR_RIGHT_TEAM = COLOR_ENEMY
COLOR_RIGHT_TEAM_OUTLINE = COLOR_ENEMY_OUTLINE
COLOR_OBSTACLE_PRIMARY = COLOR_OBSTACLE_FILL

# Gameplay tuning
PLAYER_MOVE_SPEED = 5
PLAYER_ROTATION_DEGREES = 5
PROJECTILE_SPEED = 10
SHOOT_COOLDOWN_FRAMES = 30
AIM_TOLERANCE_DEGREES = 10
MAX_EPISODE_STEPS = 1200

# Enemy behavior / curriculum
STARTING_LEVEL = 1
MAX_LEVEL = 3
MIN_EPISODES_PER_LEVEL = 300
LEVEL_UP_AVG_REWARD = {2: 10.0, 3: 25.0}  # target Avg100 needed to enter each level
DEFAULT_OBSTACLES = 8
SPAWN_Y_OFFSET = 80
SAFE_RADIUS = 100
MIN_OBSTACLE_SECTIONS = 2
MAX_OBSTACLE_SECTIONS = 5

# Rendering
FONT_SIZE = 24

# Model and training
MODEL_CHECKPOINT_PATH = "model/bang_dqn.pth"
MODEL_BEST_PATH = "model/bang_dqn_best.pth"
LOAD_PREVIOUS_MODEL = False

NUM_INPUT_FEATURES = 16
NUM_ACTIONS = 6

ACTION_MOVE_FORWARD = 0
ACTION_MOVE_BACKWARD = 1
ACTION_TURN_LEFT = 2
ACTION_TURN_RIGHT = 3
ACTION_SHOOT = 4
ACTION_WAIT = 5

REPLAY_BUFFER_SIZE = 150_000
BATCH_SIZE = 512
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-5
GAMMA = 0.98

EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY_PER_EPISODE = 0.995
EPSILON_BOOST_ON_LEVEL_UP = 0.20
TARGET_SYNC_EVERY = 500
GRAD_CLIP_NORM = 10.0

HIDDEN_DIMENSIONS = [128, 128, 64]
DROPOUT_RATE = 0.1

# Reward shaping
REWARD_HIT_ENEMY = 40.0
REWARD_WIN_ROUND = 120.0
PENALTY_GOT_HIT = -50.0
PENALTY_LOSE_ROUND = -120.0
REWARD_AIMING = 0.2
REWARD_APPROACH_ENEMY_SCALE = 0.05
PENALTY_TIME_STEP = -0.02
PENALTY_BAD_SHOT = -0.15
REWARD_GOOD_SHOT = 1.0
REWARD_DODGE_PROJECTILE = 0.08
